---
- hosts: web
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True      
  - name: Deploy War File
    maven_artifact: group_id=old artifact_id=gameoflige extension=war repository_url=http://3.135.224.240:8081/nexus/content/repositories/{{java}} username={{ admin }} password={{ admin123 }} 
  - name: Start Tomcat
    service: name=tomcat state=started
