---
- hosts: web
  become: true
  tasks:
  - name: Stop Tomcat
    shell: /etc/init.d/tomcatstop
  - name: Check that war file exist
    stat:
      path: /opt/apache-tomcat-8.5.51/webapps/gameoflife.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /opt/apache-tomcat-8.5.51/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /opt/apache-tomcat-8.5.51/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /opt/apache-tomcat-8.5.51/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://3.12.104.45:8081/nexus/content/repositories/java/maven/redirect?r=java&g=CI_CD&a=gameoflife&p=war&v=LATEST
       dest: /opt/apache-tomcat-8.5.51/webapps/gameoflife.war
  - name: Stop Tomcat
    shell: /etc/init.d/tomcatstart
