---
- hosts: web
  become: true
  tasks:
  - name: Stop Tomcat
    shell: /etc/init.d/tomcatstop
  - name: Clean the existing war file
    file:
      path: /opt/apache-tomcat-8.5.51/webapps/gameoflife.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://3.133.98.64:8081/nexus/content/repositories/java/maven/redirect?r=java&g=CI_CD&a=gameoflife1&p=war&v=LATEST
       dest: /opt/apache-tomcat-8.5.51/webapps/gameoflife.war

 
